server:
  port: 8888
spring:
  application:
    name: cheese-cli-boot
  profiles:
    active: dev
# log
logging:
  file: log/${spring.application.name}/${spring.application.name}.info.log
  level:
    com:
      favorites: DEBUG
      # 业务模块 DEBUG或者ERROR
      cheese:
        boot:
          modules: DEBUG
    org:
      springframework:
        web: DEBUG



