#\u81EA\u5B9A\u4E49\u7684\u5B89\u5168\u914D\u7F6E\uFF0CskipUrl\u4E3A\u4E0D\u9700\u8981\u62E6\u622A\u7684url
cheese:
  secure:
    enabled: true
    skipUrl:
      - /notify/**
      - /client-dispatch/**
      - /cheese/car/check
      - /api/login
      - /api/verifyCode
      # \u4E34\u65F6\u653E\u5F00\u6D41\u7A0B\u6A21\u5757\u66B4\u9732\u7684\u63A5\u53E3
      - /api/workflow/**
      # \u653E\u5F00admin\u76D1\u63A7\u7AEF\u70B9 \u5355\u4F53\u73AF\u5883 server\u548Cclient\u5728\u540C\u4E00\u4E2A\u5E94\u7528\u5185
      - /actuator/**
      - /admin/instances
    skipOther:
      - /css/**
      - /js/**
      - /index.html
      - /img/**
      - /fonts/**
      - /favicon.ico
  # \u6A21\u62DF\u7528\u6237\uFF0C\u5B9E\u9645\u9700\u8981\u4ECE\u6570\u636E\u5E93\u4E2D\u8BFB\u53D6
  user:
    userDetails:
      - kitty,$2a$10$35j6YJot7sJABEXEdNsCQeu8aO5uXCEiSoGl0t9nE9xxXouteeXhW
      - lily,lily
      - lomz,lomz
      - admin,admin
      - test,test
      - wyadmin,admin
spring:
  main:
    # \u6682\u65F6\u89E3\u51B3bean\u5B9E\u4F8B\u51B2\u7A81\u95EE\u9898\uFF0C\u73B0\u5B58\u5728bean\uFF1AmethodSecurityInterceptor\uFF0Corg/activiti/spring/boot/MethodSecurityConfig.class --- org/springframework/security/config/annotation/method/configuration/GlobalMethodSecurityConfiguration.class
    allow-bean-definition-overriding: true
  # Activity7
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    serialize-p-o-j-os-in-variables-to-json: false
  # DB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tms1cd_design?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 60000
  # Admin
  boot:
    admin:
      # \u5BA2\u6237\u7AEF\u7684\u914D\u7F6E
      client:
        # \u914D\u7F6E\u7684\u670D\u52A1\u7AEF\u7684url\u5730\u5740 (\u5F53\u524D\u5BA2\u6237\u7AEF\u4E0E\u670D\u52A1\u7AEF\u5728\u540C\u4E00\u4E2A\u5E94\u7528\u5185)
        url: http://localhost:8888/admin
      # \u670D\u52A1\u7AEF\u7684\u914D\u7F6E
      context-path: /admin/
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always